# 04/03/2022 04:56 am - SSN
# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  #RestoreBuildProjects: '**/*.csproj'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  WebAppName: 'ps-253-wpf-publish-20220403'
# 04/03/2022 05:21 am - SSN - Copied from SamNiyazi2.DevSitesIndex pipeline.
  connectedServiceName: 'ssn-service-connection--default-web-centralus-20220321'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

# 04/03/2022 05:14 am - SSN - Added
- task: DotNetCoreCLI@2
  displayName: Publish
  inputs:
    command: 'publish'
    publishWebProjects: true
    arguments: '--configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory)'
# 04/03/2022 07:16 am - SSN - Deactivate
# Change WEBSITE_RUN_FROM_PACKAGE in app settings to 0. Currently at 1.
    # zipAfterPublish: True
  enabled: true
  
# 04/03/2022 05:14 am - SSN - Added
- task: AzureWebApp@1
  displayName: 'Azure Web App Deploy: $(WebAppName) '
  inputs:
    azureSubscription: '$(connectedServiceName)'
    appType: webApp
    appName: '$(WebAppName)'
    package: '$(build.artifactstagingdirectory)/**/*.zip'
  enabled: true

# 04/03/2022 05:14 am - SSN - Added
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'
  condition: succeededOrFailed()
  enabled: true
