
version: "3.9"
services:
  web:
    build:
        context: ./
        dockerfile: Dockerfile
    ports:
      - "80:80"

  pauseapp:
#    image: mcr.microsoft.com/dotnet/core/aspnet:3.1
    build: 
        context: ./PauseApp
        dockerfile: Dockerfile-dotnet
        # args: 
        #   root_dir: dir c:\app\.
